### ISSUE TITLE
qannotate homopolymer mode throws unhelpful exception

### ISSUE THREAD

**Issue by holmeso** [AdamaJava/adamajava#54]
Liam is running qannotate's homopolymer mode (as part of the annotation process rather than in isolation) and it is giving the following error:

```
18:09:35.374 [main] TOOL au.edu.qimr.qannotate.modes.HomoplymersMode - window size for homoplymers: 100
18:09:35.374 [main] TOOL au.edu.qimr.qannotate.modes.HomoplymersMode - report homoplymers base on both side of variants: 10
java.lang.ArrayIndexOutOfBoundsException: -1
        at au.edu.qimr.qannotate.modes.HomoplymersMode.findHomopolymer(HomoplymersMode.java:194)
        at au.edu.qimr.qannotate.modes.HomoplymersMode.getHomopolymerData(HomoplymersMode.java:134)
        at au.edu.qimr.qannotate.modes.HomoplymersMode.annotate(HomoplymersMode.java:95)
        at au.edu.qimr.qannotate.modes.HomoplymersMode.addAnnotation(HomoplymersMode.java:81)
        at au.edu.qimr.qannotate.modes.HomoplymersMode.<init>(HomoplymersMode.java:61)
        at au.edu.qimr.qannotate.Main.main(Main.java:42)
main java.lang.ArrayIndexOutOfBoundsException: -1 : -1
```

Would it be possible to throw an exception that has some more information to hopefully allow the user to address whatever issue has arisen?

**To Reproduce**
1. Run qannotate homopolymer mode against the following vcf:
`/working/genomeinfo/cromwell-test/cromwell-executions/somaticDnaARGSToMaf/4c9d0a08-d159-4459-abbc-d019af76eb89/call-homAnno/inputs/-1847501406/21110ac3-7403-4f2a-83c7-0d862ff86034.merged.dbsnp.germ.vcf.gz`
2. See error

Note that Liam is running this process against some modified bam files - this is not happening as part of the production workflow, and so the cause of the error may not be "standard"

**Comment by holmeso** [comment]
OK, so there is a bug in `qannotate`'s `homopolymer` mode code where if there is a variant at position 1 (yeah, I know...) then an `ArrayOutOfBoundsException` is thrown.

What would biologists like to see in the HOM field when there is a variant at position 1?

**Comment by holmeso** [comment]
A fix has gone in for the `ArrayOutOfBoundsException` has gone in, and results in the following entry in the `INFO` field after applying the homopolymer annotation:
```
HOM=2,gAATTCATTCA
```

If this is not desirable, please leave a comment with the solution that you would rather have.
Thanks!

**Comment by holmeso** [comment]
Closing as its been a couple of months and no negative (or positive) feedback.
Please re-open if required
